urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import *
app_name='online'
urlpatterns=[
    path('',views.home,name='home'),
    path('add',views.log,name='log'),
    path('sign',views.sign,name='sign'),
    path('admin',views.admin,name='admin'),
    path('signupsuccess',views.signupsuccess,name='success'),
    path('loginsuccess',views.loginsuccess,name='loginsuc'),
    path('register',views.register,name='register'),
    path('login2',views.loginn,name='loginn'),
    path('logout',views.logout,name='logout'),
    path('admin',views.adminn,name='admin'),
    path('addquestions',views.addquestions,name='addque'),
    path('showquestions',views.showquestions,name='showque'),
    path('showstudents',views.showstudents,name="shotstu"),
    path('aboutstudents',views.aboutstudents,name='astu'),
    path('show',views.show,name='show'),
    path('addsubjects',views.addsubjects,name='addsub'),
    path('students',views.students,name='students'),
    path('subjects',views.subjects,name='subjects'),
    path('subadd',views.subadd,name='subadd'),
    path('image_upload', hotel_image_view, name = 'image_upload'),
    path('success', success, name = 'success'),
    path('hotel_images', display_hotel_images, name = 'hotel_images'),
    path('uploadque',views.uploadque,name='uploadque'),
    path('profile',views.profile,name='profile'),
    path('search',views.search,name='search'),
    path('gotosub/<str:test> <str:email>',views.gotosub,name='gotosub'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('gotosub/enroll',views.enroll,name='enroll'),
    path('gotosub/onemark',views.questionsshow,name='questionshow'),
    path('gotosub/twomark',views.questionsshow,name='questionshow'),
    path('gotosub/threemark',views.questionsshow,name='questionshow'),
    path('gotosub/marksevaluation',views.marksevaluation,name='marksevaluation'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/aboutstu.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ADMIN PAGE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    <style>
               .btn-default {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(108, 88, 179, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(108, 89, 179, 0.75);
  border-radius: 40px;
  background: transparent;
  transition: all 0.3s ease 0s;
}

.btn-default:hover {
  color: #FFF;
  background: rgba(108, 88, 179, 0.75);
  border: 2px solid rgba(108, 89, 179, 0.75);
}

.btn-primary {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(58, 133, 191, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}
.btn-success {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(20, 179, 20, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}


.btn-primary:hover {
  color: #FFF;
  background: rgba(58, 133, 191, 0.75);
  border: 2px solid rgba(58, 133, 191, 0.75);
}

.card{
  border: #FFF;
}
.modal-body{
  font-weight: 400;
}
.carousel-inner img {
      width: 50%; /* Set width to 100% */
      margin: auto;
      min-height:100px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }

    }
    </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-expand-sm bg-primary ">
    <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <br>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        {% load static %}
        <a class="navbar-brand mr-auto navbar-left" href="#"><img src="{% static 'images/capture4.jpg' %}" height="70" width="170"></a>
         </div>
          <br>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><span class="fa fa-home fa-lg"></span>Home</a></li>
          <li><a href="#"><span class="fa fa-info fa-lg"></span>Aboutus</a></li>
          <li><a href="#"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
        </ul>
        <br><ul class="nav navbar-nav navbar-right ">

          <li><a href="{% url 'online:addque' %}"><span class="fa fa-address-card fa-lg"></span>Add Questions</a></li>
          <li><a href="{% url 'online:showque' %}"><span class="fa fa-address-card fa-lg"></span>Show Questions</a></li>
          <li><a href="{% url 'online:image_upload' %}"><span class="fa fa-address-card fa-lg"></span>Add Subjects</a></li>
          <li><a href="{% url 'online:hotel_images' %}"><span class="fa fa-address-card fa-lg"></span>Subjects</a></li>
          <li><a href="{% url 'online:students' %}"><span class="fa fa-address-card fa-lg"></span>Students</a></li>
          <li><a href="{% url 'online:astu' %}"><span class="fa fa-address-card fa-lg"></span>About Students</a></li>
          <li><a href="{% url 'online:logout' %}"><span class="fa fa-address-card fa-lg"></span>Logout</a></li>


            </ul>
 </div>
    </div>
  </div><br>
  </nav>

<form method="post" action="showstudents">
    {% csrf_token %}
    Student name:<input type="text" name="email"> <br>
<input type="submit" value="show">
    </form>

<table border="1">
    <th>Emailid</th><th>Password</th>
{% for i in  data %}
    {% ifequal i.emailid email %}
        <tr>
            <td>{{ i.subjectname }}</td>
            <td>{{ i.date }}</td>
    {% endifequal %}
{% endfor %}
</body>
</html>

templates/addsub.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ADMIN PAGE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    <style>
               .btn-default {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(108, 88, 179, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(108, 89, 179, 0.75);
  border-radius: 40px;
  background: transparent;
  transition: all 0.3s ease 0s;
}

.btn-default:hover {
  color: #FFF;
  background: rgba(108, 88, 179, 0.75);
  border: 2px solid rgba(108, 89, 179, 0.75);
}

.btn-primary {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(58, 133, 191, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}
.btn-success {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(20, 179, 20, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}


.btn-primary:hover {
  color: #FFF;
  background: rgba(58, 133, 191, 0.75);
  border: 2px solid rgba(58, 133, 191, 0.75);
}

.card{
  border: #FFF;
}
.modal-body{
  font-weight: 400;
}
.carousel-inner img {
      width: 50%; /* Set width to 100% */
      margin: auto;
      min-height:100px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }

    }
    </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-expand-sm bg-primary ">
    <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <br>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        {% load static %}
        <a class="navbar-brand mr-auto navbar-left" href="#"><img src="{% static 'images/capture4.jpg' %}" height="70" width="170"></a>
         </div>
          <br>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><span class="fa fa-home fa-lg"></span>Home</a></li>
          <li><a href="#"><span class="fa fa-info fa-lg"></span>Aboutus</a></li>
          <li><a href="#"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
        </ul>
        <br><ul class="nav navbar-nav navbar-right ">

          <li><a href="{% url 'online:addque' %}"><span class="fa fa-address-card fa-lg"></span>Add Questions</a></li>
          <li><a href="{% url 'online:showque' %}"><span class="fa fa-address-card fa-lg"></span>Show Questions</a></li>
          <li><a href="{% url 'online:image_upload' %}"><span class="fa fa-address-card fa-lg"></span>Add Subjects</a></li>
          <li><a href="{% url 'online:hotel_images' %}"><span class="fa fa-address-card fa-lg"></span>Subjects</a></li>
          <li><a href="{% url 'online:students' %}"><span class="fa fa-address-card fa-lg"></span>Students</a></li>
          <li><a href="{% url 'online:astu' %}"><span class="fa fa-address-card fa-lg"></span>About Students</a></li>
          <li><a href="{% url 'online:logout' %}"><span class="fa fa-address-card fa-lg"></span>Logout</a></li>


            </ul>
 </div>
    </div>
  </div><br>
  </nav>
<form name="form1" method="post" action="subadd">
    {% csrf_token %}
    <input type="text" name="subjectname"><br>
    <input type="file" name="upload"><br>
    <input type="submit" value="submit">
</form>
</body>
</html>

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ADMIN PAGE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    <style>
               .btn-default {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(108, 88, 179, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(108, 89, 179, 0.75);
  border-radius: 40px;
  background: transparent;
  transition: all 0.3s ease 0s;
}

.btn-default:hover {
  color: #FFF;
  background: rgba(108, 88, 179, 0.75);
  border: 2px solid rgba(108, 89, 179, 0.75);
}

.btn-primary {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(58, 133, 191, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}
.btn-success {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(20, 179, 20, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}


.btn-primary:hover {
  color: #FFF;
  background: rgba(58, 133, 191, 0.75);
  border: 2px solid rgba(58, 133, 191, 0.75);
}

.card{
  border: #FFF;
}
.modal-body{
  font-weight: 400;
}
.carousel-inner img {
      width: 50%; /* Set width to 100% */
      margin: auto;
      min-height:100px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }

    }
    </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-expand-sm bg-primary ">
    <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <br>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        {% load static %}
        <a class="navbar-brand mr-auto navbar-left" href="#"><img src="{% static 'images/capture4.jpg' %}" height="70" width="170"></a>
         </div>
          <br>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><span class="fa fa-home fa-lg"></span>Home</a></li>
          <li><a href="#"><span class="fa fa-info fa-lg"></span>Aboutus</a></li>
          <li><a href="#"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
        </ul>
        <br><ul class="nav navbar-nav navbar-right ">

          <li><a href="{% url 'online:addque' %}"><span class="fa fa-address-card fa-lg"></span>Add Questions</a></li>
          <li><a href="{% url 'online:showque' %}"><span class="fa fa-address-card fa-lg"></span>Show Questions</a></li>
          <li><a href="{% url 'online:image_upload' %}"><span class="fa fa-address-card fa-lg"></span>Add Subjects</a></li>
          <li><a href="{% url 'online:hotel_images' %}"><span class="fa fa-address-card fa-lg"></span>Subjects</a></li>
          <li><a href="{% url 'online:students' %}"><span class="fa fa-address-card fa-lg"></span>Students</a></li>
          <li><a href="{% url 'online:astu' %}"><span class="fa fa-address-card fa-lg"></span>About Students</a></li>
          <li><a href="{% url 'online:logout' %}"><span class="fa fa-address-card fa-lg"></span>Logout</a></li>


            </ul>
 </div>
    </div>
  </div><br>
  </nav>


</body>
</html>

templates/hotel_image_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ADMIN PAGE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    <style>
               .btn-default {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(108, 88, 179, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(108, 89, 179, 0.75);
  border-radius: 40px;
  background: transparent;
  transition: all 0.3s ease 0s;
}

.btn-default:hover {
  color: #FFF;
  background: rgba(108, 88, 179, 0.75);
  border: 2px solid rgba(108, 89, 179, 0.75);
}

.btn-primary {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(58, 133, 191, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}
.btn-success {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(20, 179, 20, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}


.btn-primary:hover {
  color: #FFF;
  background: rgba(58, 133, 191, 0.75);
  border: 2px solid rgba(58, 133, 191, 0.75);
}

.card{
  border: #FFF;
}
.modal-body{
  font-weight: 400;
}
.carousel-inner img {
      width: 50%; /* Set width to 100% */
      margin: auto;
      min-height:100px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }

    }
    </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-expand-sm bg-primary ">
    <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <br>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        {% load static %}
        <a class="navbar-brand mr-auto navbar-left" href="#"><img src="{% static 'images/capture4.jpg' %}" height="70" width="170"></a>
         </div>
          <br>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><span class="fa fa-home fa-lg"></span>Home</a></li>
          <li><a href="#"><span class="fa fa-info fa-lg"></span>Aboutus</a></li>
          <li><a href="#"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
        </ul>
        <br><ul class="nav navbar-nav navbar-right ">

          <li><a href="{% url 'online:addque' %}"><span class="fa fa-address-card fa-lg"></span>Add Questions</a></li>
          <li><a href="{% url 'online:showque' %}"><span class="fa fa-address-card fa-lg"></span>Show Questions</a></li>
          <li><a href="{% url 'online:image_upload' %}"><span class="fa fa-address-card fa-lg"></span>Add Subjects</a></li>
          <li><a href="{% url 'online:hotel_images' %}"><span class="fa fa-address-card fa-lg"></span>Subjects</a></li>
          <li><a href="{% url 'online:students' %}"><span class="fa fa-address-card fa-lg"></span>Students</a></li>
          <li><a href="{% url 'online:astu' %}"><span class="fa fa-address-card fa-lg"></span>About Students</a></li>
          <li><a href="{% url 'online:logout' %}"><span class="fa fa-address-card fa-lg"></span>Logout</a></li>


            </ul>
 </div>
    </div>
  </div><br>
  </nav>

    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>

<body>
    <form name="form1" method="post" action="loginsuccess">
        {% csrf_token %}
        UserName:<input type="text" name="username"><br>
        Password:<input type="password" name="pwd"><br>
        <input type="submit" value="Login">
    </form>
</body>
</html>

templates/showquestions.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ADMIN PAGE</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap-social/bootstrap-social.css">

  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    <style>
               .btn-default {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(108, 88, 179, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(108, 89, 179, 0.75);
  border-radius: 40px;
  background: transparent;
  transition: all 0.3s ease 0s;
}

.btn-default:hover {
  color: #FFF;
  background: rgba(108, 88, 179, 0.75);
  border: 2px solid rgba(108, 89, 179, 0.75);
}

.btn-primary {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(58, 133, 191, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}
.btn-success {
  font-family: Raleway-SemiBold;
  font-size: 13px;
  color: rgba(58, 133, 191, 0.75);
  letter-spacing: 1px;
  line-height: 15px;
  border: 2px solid rgba(20, 179, 20, 0.75);
  border-radius: 40px;
  background: #FFF;
  transition: all 0.3s ease 0s;
}


.btn-primary:hover {
  color: #FFF;
  background: rgba(58, 133, 191, 0.75);
  border: 2px solid rgba(58, 133, 191, 0.75);
}

.card{
  border: #FFF;
}
.modal-body{
  font-weight: 400;
}
.carousel-inner img {
      width: 50%; /* Set width to 100% */
      margin: auto;
      min-height:100px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none;
    }

    }
    </style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-expand-sm bg-primary ">
    <div class="container-fluid">
      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <br>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        {% load static %}
        <a class="navbar-brand mr-auto navbar-left" href="#"><img src="{% static 'images/capture4.jpg' %}" height="70" width="170"></a>
         </div>
          <br>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><span class="fa fa-home fa-lg"></span>Home</a></li>
          <li><a href="#"><span class="fa fa-info fa-lg"></span>Aboutus</a></li>
          <li><a href="#"><span class="fa fa-address-card fa-lg"></span>Contact</a></li>
        </ul>
        <br><ul class="nav navbar-nav navbar-right ">

          <li><a href="{% url 'online:addque' %}"><span class="fa fa-address-card fa-lg"></span>Add Questions</a></li>
          <li><a href="{% url 'online:showque' %}"><span class="fa fa-address-card fa-lg"></span>Show Questions</a></li>
          <li><a href="{% url 'online:image_upload' %}"><span class="fa fa-address-card fa-lg"></span>Add Subjects</a></li>
          <li><a href="{% url 'online:hotel_images' %}"><span class="fa fa-address-card fa-lg"></span>Subjects</a></li>
          <li><a href="{% url 'online:students' %}"><span class="fa fa-address-card fa-lg"></span>Students</a></li>
          <li><a href="{% url 'online:astu' %}"><span class="fa fa-address-card fa-lg"></span>About Students</a></li>
          <li><a href="{% url 'online:logout' %}"><span class="fa fa-address-card fa-lg"></span>Logout</a></li>


            </ul>
 </div>
    </div>
  </div><br>
  </nav>

<form method="post" action="show">
    {% csrf_token %}

Course Name:<input type="text" name="course"><br>
    Marks :<input type="text" name="marks"><br>
    <input type="submit" value="show">

    {% for i in questions %}
        {% ifequal i.subname course %}
            {% ifequal i.marks marks %}
                    <li>
                    {{ i.question }}<br>
                    <input type="radio" name="{{ i.question }}" value={{ i.option1 }}>{{ i.option1 }}<br>
                    <input type="radio" name="{{ i.question }}" value={{ i.option2 }}>{{ i.option2 }}<br>
                    <input type="radio" name="{{ i.question }}" value={{ i.option3 }}>{{ i.option3 }}<br>
                    <input type="radio" name="{{ i.question }}" value={{ i.option4 }}>{{ i.option4 }}<br>
                    </li>
            {% endifequal %}
        {% endifequal %}

      {% endfor %}
</form>
</body>
</html>